# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            GANsNotGains
splitTitle:       'GANs&#10;Not&#10;Gains'
tagline:          'CS4476 Project Page'
description:      'Generating artwork with GANs'
url:              https://GANsNotGains.github.io/
baseurl:          /

author:
  name:           'Matthew Kaufer'
  url:            https://github.com/mjkaufer

github:
  repo:           https://github.com/GANsNotGains